# fly.toml app configuration file generated for dutchiedutchbot on 2023-05-25T15:32:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dutchiedutchbot"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "80"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
